language: ruby
env:
  global:
    secure: igUfHIKPhOaVQ4uh6K6XDxVR6pGVDOE8g9m+3nm/jXU/jhRog6v2e/yjQ+OJo9qOI7MK0QC3eKhBONRgtg0r/Z0qYRkUenbbItrjc82HCUESKJMMYf2ZLrLkjJs6EtVShCADoK2zJ5m2LhNWlgH/yZHAqu1f4lfMIfjv5qq72Hs=
